name: Deploy to AKS using Helm (Pull from ACR)

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 3: Log in to Azure using Service Principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Set up AKS credentials
    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    # Step 5: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name "${{ secrets.AZURE_REGISTRY_URL }}"

    # Step 6: Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Step 7: Deploy using Helm
    - name: Deploy to AKS using Helm
      run: |
        helm upgrade --install my-release ./backend-chart \
          --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/backend \
          --set image.tag=latest \
          --namespace default

    # Step 8: Verify the deployment
    - name: Verify Deployment
      run: |
        kubectl get pods