name: Deploy to AKS using Helm (Pull from ACR)

on:
  workflow_run:
    workflows: ["Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Azure using Service Principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up AKS credentials
    - name: Set up AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    # Step 4: Log in to Azure Container Registry (ACR)
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name "${{ secrets.AZURE_REGISTRY_URL }}"

    # Step 5: Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Step 6: Uninstall previous backend release (if exists)
    - name: Uninstall backend release (if exists)
      run: |
        helm uninstall backend-release || true  # Ignore error if release does not exist

    # Step 7: Deploy using Helm for backend
    - name: Deploy to AKS using Helm for backend
      run: |
        helm upgrade --install backend-release ./backend-chart \
          --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/backend \
          --set image.tag=latest \
          --debug

    # Step 8: Uninstall previous frontend release (if exists)
    - name: Uninstall frontend release (if exists)
      run: |
        helm uninstall frontend-release || true  # Ignore error if release does not exist

    # Step 9: Deploy using Helm for frontend
    - name: Deploy to AKS using Helm for frontend
      run: |
        helm upgrade --install frontend-release ./frontend-chart \
          --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/frontend \
          --set image.tag=latest \
          --debug

    # Step 10: Verify the deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
